services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open_webui
    restart: unless-stopped
    networks:
      - hermes_network
    ports:
      - "127.0.0.1:3200:8080"
    volumes:
      - open-webui-data:/app/backend/data
    env_file:
      - .env
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  open-webui-data: {}

networks:
  hermes_network:
    external: true
